### ISSUE TITLE
想问下老哥是怎么解决这个报错的

### ISSUE THREAD

**Issue by PINEAA** [yusanshi/Greedy_Snake_Verilog#2]
[Timing 38-316] Clock period '100.000' specified during out-of-context synthesis of instance 'nolabel_line115/nolabel_line28' at clock pin 'CLK' is different from the actual clock period '10.000', this can lead to different synthesis results.

**Comment by yusanshi** [comment]
你好，请问这个是 Warning 么？
要是 Warning 的话你看看会影响实际下板么？
时间过了好久了我也忘记了。记得当时是有一堆 Warnings，发现上板没问题就没管了。
所以好多 Warning 我也不会处理😁
